language: java
sudo: required
dist: xenial
jdk:
  - openjdk8
cache:
  directories:
    - "${HOME}/.m2"
branches:
  only:
    - master
script:
    - mvn package
notifications:
    email:
        - ryanchan@amazon.com
